# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Newton-Raphson algorithm for solving optimal log utiltiy under uniform distributions
#'
#' @param interval the interval for the uniform distribution
#' @param rate the risk-neutral rate
#' @param n the number of iterations to take in the NR method.
#'
#' @description {For finding the root of the function \eqn{h(x)=\log((1+bx)/(1+ax))/(b-a)-x}.}
#' @details {The algorithm is on wikipedia and quite straightforward.}
kellyUniform <- function(interval, rate = 0.0, n = 500L) {
    .Call(`_kellyfractions_kellyUniform`, interval, rate, n)
}

